---
- name: Call multiple child playbooks for apache2 configurations
  hosts: all
  tasks:
    - name: Call multiple playbooks
      include_tasks:  "{{item}}"
      with_items:
        - install.yml
        - edit_index.yml
        - restart.yml
        - check_url_response.yml
