---
- name: Implementing handlers
  hosts: all
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
      notify: Check apache response
    - name: Edit the index.hmtl file
      copy:
        content: "Welcome to new IntelliQ"
        dest: /var/www/html/index.html
      notify: Restart apache
  handlers:
    - name: Restart apache
      service:
        name: apache2
        state: restarted
    - name: Check apache response
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.23.201
        - http://172.31.30.222
...
