---
- name: capture OS info of all the servers
  hosts: all
  tasks:
    - name: capture OS name
      debug:
        var: "{{ansible_distribution}}"
    - name: Capture OS version
      debug:
        var: "{{ansible_distribution_version}}"
    - name: capture OS major version no
      debug:
        var: "{{ansible_distribution_major_version}}"

...
