---
- name: Configure Apache/HTTPD on all servers
  hosts: all
  become: yes

  vars:
    web_pkg: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    web_service: "{{ web_pkg }}"
    web_root: /var/www/html

  tasks:
    - name: Install Apache/HTTPD
      package:
        name: "{{ web_pkg }}"
        state: present
        update_cache: yes

    - name: Ensure web root directory exists
      file:
        path: "{{ web_root }}"
        state: directory
        mode: '0755'

    - name: Deploy custom index.html file
      copy:
        content: "Welcome to IntelliQIT — managed by Ansible"
        dest: "{{ web_root }}/index.html"

    - name: Enable and restart web server
      service:
        name: "{{ web_service }}"
        state: restarted
        enabled: yes

    - name: Verify HTTP response on all servers
      uri:
        url: "{{ item }}"
        status_code: 200
      loop:
        - http://172.31.23.201
        - http://172.31.30.222
        - http://172.31.26.3

